### ISSUE TITLE
failed to load. something about java version.

### ISSUE THREAD

**Issue by RustyDagger** [LittleBigBug/acoworth#8]
So its been doing this on my server for sometime it would seem iv only now just caught it,
I think it started with version 1.5.0. No idea how to fix it to make it load my servers running java 1.8....

`>....     [15:26:04 ERROR: Could not load 'plugins/AcoWorth-1.5.0.jar' in folder 'plugins']
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/yasfu/acoworth/AcoWorthPlugin has been compiled by a more recent ve
rsion of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:140) ~[patched_1.15.2.jar:git-Paper-205]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-205]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-205]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-205]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-205]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Paper-205]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.UnsupportedClassVersionError: net/yasfu/acoworth/AcoWorthPlugin has been compiled by a more recent version of the Java Runtime (clas
s file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-205]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-205]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.15.2.jar:git-Paper-205]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[patched_1.15.2.jar:git-Paper-205]
    ... 6 more`

**Comment by LittleBigBug** [comment]
I didn't pay attention to what JDK i was using to build this with. I should probably re-release it using Java 8, but it seems it is using 53.0 which is Java 9
I'm pretty busy at the moment but I will fix this asap, if you can update to java 9 that will fix this. Regardless, I should probably build on java 8...

**Comment by Rand404** [comment]
Yeah, I have this issue too. Will keep the repo on watch until java 8 release.

**Comment by LittleBigBug** [comment]
[New release is built with OpenJDK 8](https://github.com/LittleBigBug/acoworth/releases/download/untagged-7462a26724bbe35a11b1/AcoWorth-1.6.jar)
